"""Cambio nombre columna nombre en tabla usuario

Revision ID: 1feb3889452e
Revises: c4fa4b2ac064
Create Date: 2021-02-04 11:20:38.652640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1feb3889452e'
down_revision = 'c4fa4b2ac064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.String(length=80), nullable=False))
    op.drop_column('usuarios', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###
