"""Initial database

Revision ID: c4fa4b2ac064
Revises: 
Create Date: 2021-02-03 19:10:26.904976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fa4b2ac064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redes_sociales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=60), nullable=False),
    sa.Column('link', sa.String(length=60), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_aplicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=60), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('fk_rol', sa.Integer(), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=30), nullable=False),
    sa.Column('apellido_materno', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fk_rol'], ['roles_aplicacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios_redes_sociales',
    sa.Column('fk_usuario', sa.Integer(), nullable=False),
    sa.Column('fk_red_social', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fk_red_social'], ['redes_sociales.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('fk_usuario', 'fk_red_social')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_redes_sociales')
    op.drop_table('usuarios')
    op.drop_table('roles_aplicacion')
    op.drop_table('redes_sociales')
    # ### end Alembic commands ###
